# config/mcbesm.conf
# Get the absolute path of the project directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

INSTANCES_DIR="$PROJECT_ROOT/instances"
TEMPLATES_DIR="$PROJECT_ROOT/templates"

# API and Versioning
API_URL="https://net-secondary.web.minecraft-services.net/api/v1.0/download/links"
INSTALLED_RECORD="$PROJECT_ROOT/version_installed.txt"
PIN_FILE="$PROJECT_ROOT/version_pin.txt"
