# config/mcbesm.conf
# Get the absolute path of the project directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

INSTANCES_DIR="$PROJECT_ROOT/instances"
TEMPLATES_DIR="$PROJECT_ROOT/templates"
